service: nestjs-serverless-template

app: nestjs-serverless-template
org: silvacodes

provider:
  name: aws
  runtime: nodejs16.x
  architecture: x86_64
  stage: production
  region: us-east-1
  memorySize: 2048
  logRetentionInDays: 1
  timeout: 15
  

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi:
          method: any
          path: /{proxy+}

plugins:
  - serverless-esbuild
  - serverless-offline

build:
  esbuild: false

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    target: 'node16'
    define: { 'process.env.NODE_ENV': '"production"' }
    platform: 'node'
    outdir: '.build'