service: nestjs-serverless-template

app: nestjs-serverless-template
org: silvacodes

provider:
  name: aws
  runtime: nodejs16.x
  architecture: x86_64
  stage: production
  region: us-east-1
  memorySize: 2048
  logRetentionInDays: 1
  timeout: 15
  environment:
    USERS_TABLE_NAME: ${self:custom.usersTable.name}
  iamRoleStatements: ${file(.aws/iam/role-statements.yml)}

resources:
  Resources:
    usersTable: ${file(.aws/db/users-table.yml)}
  

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi:
          method: any
          path: /{proxy+}

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dotenv-plugin

build:
  esbuild: false

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    target: 'node16'
    define: { 'process.env.NODE_ENV': '"production"' }
    platform: 'node'
    outdir: '.build'
    external: ['class-transformer/storage']
  dotenv:
    path: ./.aws/${self:provider.stage}.env
  usersTable:
    name: ${self:service}-${self:provider.stage}-users
    arn: !GetAtt usersTable.Arn
